include Make.defines

PROGS =	 client server

OPTIONS = -DUNIX  -DUSE_SIGACTION -DANSI

LIBS += -lrt

COBJECTS =	functions.o 
CSOURCES =	functions.c 

CPLUSOBJECTS = 

COMMONSOURCES =

CPLUSSOURCES =

all:	${PROGS}


client:	client.o $(CPLUSOBJECTS) $(COBJECTS) $(LIBS) $(COMMONSOURCES) $(SOURCES)
		${CC} ${LINKOPTIONS}  $@ client.o $(CPLUSOBJECTS) $(COBJECTS) $(LIBS) $(LINKFLAGS)


server:	server.o $(CPLUSOBJECTS) $(COBJECTS)
		${CC} ${LINKOPTIONS} $@ server.o $(CPLUSOBJECTS) $(COBJECTS) $(LIBS) $(LINKFLAGS)


.cc.o:	$(HEADERS)
	$(CPLUS) $(CPLUSFLAGS) $(OPTIONS) $<

.c.o:	$(HEADERS)
	$(CC) $(CFLAGS) $(OPTIONS) $<



backup:
	rm -f *.tar.gz
	tar -cvzf hw2.tar.gz *

clean:
		rm -f ${PROGS} ${CLEANFILES} *.tar.gz

depend:
		makedepend client.c server.c  $(CFLAGS) $(HEADERS) $(SOURCES) $(COMMONSOURCES) $(CSOURCES)
#		mkdep $(CFLAGS) $(HEADERS) $(SOURCES) $(COMMONSOURCES) $(CSOURCES)

# DO NOT DELETE

client.o: defs.h /usr/include/stdio.h /usr/include/features.h
client.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
client.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
client.o: /usr/include/gnu/stubs-64.h /usr/include/bits/types.h
client.o: /usr/include/bits/typesizes.h /usr/include/libio.h
client.o: /usr/include/_G_config.h /usr/include/wchar.h
client.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
client.o: /usr/include/stdlib.h /usr/include/sys/types.h /usr/include/time.h
client.o: /usr/include/endian.h /usr/include/bits/endian.h
client.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
client.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
client.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
client.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
client.o: /usr/include/errno.h /usr/include/bits/errno.h
client.o: /usr/include/linux/errno.h /usr/include/asm/errno.h
client.o: /usr/include/asm-generic/errno.h
client.o: /usr/include/asm-generic/errno-base.h /usr/include/string.h
client.o: /usr/include/xlocale.h /usr/include/netinet/in.h
client.o: /usr/include/stdint.h /usr/include/bits/wchar.h
client.o: /usr/include/sys/socket.h /usr/include/sys/uio.h
client.o: /usr/include/bits/uio.h /usr/include/bits/socket.h
client.o: /usr/include/bits/sockaddr.h /usr/include/asm/socket.h
client.o: /usr/include/asm-generic/socket.h /usr/include/asm/sockios.h
client.o: /usr/include/asm-generic/sockios.h /usr/include/bits/in.h
client.o: /usr/include/arpa/inet.h /usr/include/netdb.h
client.o: /usr/include/rpc/netdb.h /usr/include/bits/netdb.h
client.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
client.o: /usr/include/bits/confname.h /usr/include/getopt.h
client.o: /usr/include/signal.h /usr/include/bits/signum.h
client.o: /usr/include/bits/siginfo.h /usr/include/bits/sigaction.h
client.o: /usr/include/bits/sigcontext.h /usr/include/bits/sigstack.h
client.o: /usr/include/bits/sigthread.h
server.o: defs.h /usr/include/stdio.h /usr/include/features.h
server.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
server.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
server.o: /usr/include/gnu/stubs-64.h /usr/include/bits/types.h
server.o: /usr/include/bits/typesizes.h /usr/include/libio.h
server.o: /usr/include/_G_config.h /usr/include/wchar.h
server.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
server.o: /usr/include/stdlib.h /usr/include/sys/types.h /usr/include/time.h
server.o: /usr/include/endian.h /usr/include/bits/endian.h
server.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
server.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
server.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
server.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
server.o: /usr/include/errno.h /usr/include/bits/errno.h
server.o: /usr/include/linux/errno.h /usr/include/asm/errno.h
server.o: /usr/include/asm-generic/errno.h
server.o: /usr/include/asm-generic/errno-base.h /usr/include/string.h
server.o: /usr/include/xlocale.h /usr/include/netinet/in.h
server.o: /usr/include/stdint.h /usr/include/bits/wchar.h
server.o: /usr/include/sys/socket.h /usr/include/sys/uio.h
server.o: /usr/include/bits/uio.h /usr/include/bits/socket.h
server.o: /usr/include/bits/sockaddr.h /usr/include/asm/socket.h
server.o: /usr/include/asm-generic/socket.h /usr/include/asm/sockios.h
server.o: /usr/include/asm-generic/sockios.h /usr/include/bits/in.h
server.o: /usr/include/arpa/inet.h /usr/include/netdb.h
server.o: /usr/include/rpc/netdb.h /usr/include/bits/netdb.h
server.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
server.o: /usr/include/bits/confname.h /usr/include/getopt.h
server.o: /usr/include/signal.h /usr/include/bits/signum.h
server.o: /usr/include/bits/siginfo.h /usr/include/bits/sigaction.h
server.o: /usr/include/bits/sigcontext.h /usr/include/bits/sigstack.h
server.o: /usr/include/bits/sigthread.h
functions.o: /usr/include/stdio.h /usr/include/features.h
functions.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
functions.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
functions.o: /usr/include/gnu/stubs-64.h /usr/include/bits/types.h
functions.o: /usr/include/bits/typesizes.h /usr/include/libio.h
functions.o: /usr/include/_G_config.h /usr/include/wchar.h
functions.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
functions.o: /usr/include/stdlib.h /usr/include/sys/types.h
functions.o: /usr/include/time.h /usr/include/endian.h
functions.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
functions.o: /usr/include/sys/select.h /usr/include/bits/select.h
functions.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
functions.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
functions.o: /usr/include/alloca.h
